name: ML Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:

    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc[dvc]

    # Step 4: Pull DVC data (if needed)
    - name: DVC Pull
      if: always()
      run: |
        dvc pull || echo "No remote or no data. Skipping DVC pull."

    # Step 5: Run DVC pipeline
    - name: Run DVC pipeline
      run: |
        dvc repro

    # Step 6: Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-artifacts
        path: |
          artifacts/
          data/
